/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pds_banque.View;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Warren
 */
public class ScreenLoanSim extends JFrame {

    /**
     * Creates new form ScreenLoanSim
     */
    public ScreenLoanSim() {
        initComponents();
        rootPane.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLeft = new javax.swing.JPanel();
        lblLoan = new javax.swing.JLabel();
        cbxLoan = new javax.swing.JComboBox<>();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblRate = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        lblinsurance = new javax.swing.JLabel();
        txtInsurance = new javax.swing.JTextField();
        lblAmountInsurance = new javax.swing.JLabel();
        txtAmountInsurance = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblCapital = new javax.swing.JLabel();
        txtCapital = new javax.swing.JTextField();
        PRight = new javax.swing.JPanel();
        lblMonthly = new javax.swing.JLabel();
        txtMonthly = new javax.swing.JTextField();
        lblMonthlyWInsurance = new javax.swing.JLabel();
        txtMonthlyWInsurance = new javax.swing.JTextField();
        lblMonthlyInsurance = new javax.swing.JLabel();
        txtMonthlyInsurance = new javax.swing.JTextField();
        lblTotalInterest = new javax.swing.JLabel();
        txtTotalInterest = new javax.swing.JTextField();
        lblTotalInsurance = new javax.swing.JLabel();
        txtTotalInsurrance = new javax.swing.JTextField();
        lblTotalLoan = new javax.swing.JLabel();
        txtTotalLoan = new javax.swing.JTextField();
        btnCaculate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation de prêt");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("windows"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        PLeft.setBackground(new java.awt.Color(255, 255, 255));

        lblLoan.setText("Type de prêt");

        cbxLoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAmount.setText("Montant du prêt");

        lblRate.setText("Taux d'interêt");

        txtRate.setEditable(false);
        txtRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRateActionPerformed(evt);
            }
        });

        lblinsurance.setText("Taux d'assurance");

        lblAmountInsurance.setText("Montant de l'assurance");

        lblDuration.setText("Durée en mois");

        lblDate.setText("Première écheance");

        lblCapital.setText("Apport initial");

        org.jdesktop.layout.GroupLayout PLeftLayout = new org.jdesktop.layout.GroupLayout(PLeft);
        PLeft.setLayout(PLeftLayout);
        PLeftLayout.setHorizontalGroup(
            PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PLeftLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblCapital)
                    .add(lblDuration)
                    .add(lblAmountInsurance)
                    .add(lblinsurance)
                    .add(lblRate)
                    .add(lblAmount)
                    .add(lblLoan)
                    .add(lblDate)
                    .add(cbxLoan, 0, 200, Short.MAX_VALUE)
                    .add(txtAmount)
                    .add(txtRate)
                    .add(txtInsurance)
                    .add(txtAmountInsurance)
                    .add(txtDuration)
                    .add(txtDate)
                    .add(txtCapital))
                .add(50, 50, 50))
        );
        PLeftLayout.setVerticalGroup(
            PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PLeftLayout.createSequentialGroup()
                .add(lblLoan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbxLoan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblAmount)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtAmount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblRate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblinsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblAmountInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtAmountInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblDuration)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblDate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblCapital)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtCapital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10))
        );

        PRight.setBackground(new java.awt.Color(255, 255, 255));
        PRight.setPreferredSize(new java.awt.Dimension(300, 500));

        lblMonthly.setText("Mensualité hors assurance");

        txtMonthly.setEditable(false);
        txtMonthly.setBackground(new java.awt.Color(204, 204, 204));
        txtMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlyActionPerformed(evt);
            }
        });

        lblMonthlyWInsurance.setText("Mensualité de l'assurance");

        txtMonthlyWInsurance.setEditable(false);
        txtMonthlyWInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthlyWInsuranceActionPerformed(evt);
            }
        });

        lblMonthlyInsurance.setText("Mensualité avec assurrance");

        txtMonthlyInsurance.setEditable(false);

        lblTotalInterest.setText("Total interets");

        txtTotalInterest.setEditable(false);

        lblTotalInsurance.setText("Total assurance");

        txtTotalInsurrance.setEditable(false);

        lblTotalLoan.setText("Cout total du prêt");

        txtTotalLoan.setEditable(false);

        org.jdesktop.layout.GroupLayout PRightLayout = new org.jdesktop.layout.GroupLayout(PRight);
        PRight.setLayout(PRightLayout);
        PRightLayout.setHorizontalGroup(
            PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PRightLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTotalInsurance)
                    .add(lblTotalInterest)
                    .add(lblMonthlyInsurance)
                    .add(lblMonthlyWInsurance)
                    .add(lblMonthly)
                    .add(lblTotalLoan)
                    .add(txtMonthly, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(txtMonthlyWInsurance)
                    .add(txtMonthlyInsurance)
                    .add(txtTotalInterest)
                    .add(txtTotalInsurrance)
                    .add(txtTotalLoan))
                .add(50, 50, 50))
        );
        PRightLayout.setVerticalGroup(
            PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PRightLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(lblMonthly)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthly, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblMonthlyWInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthlyWInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblMonthlyInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthlyInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalInterest)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalInterest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalInsurrance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalLoan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalLoan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(65, 65, 65))
        );

        btnCaculate.setText("Calculer");
        btnCaculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaculateActionPerformed(evt);
            }
        });

        btnSave.setText("Enregister");

        btnBack.setText("Retour");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .add(PLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 40, Short.MAX_VALUE)
                .add(PRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnCaculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(PLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(btnCaculate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .add(btnSave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnBack, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRateActionPerformed

    private void txtMonthlyWInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlyWInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlyWInsuranceActionPerformed

    private void btnCaculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCaculateActionPerformed

    private void txtMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthlyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenLoanSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenLoanSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenLoanSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenLoanSim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenLoanSim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PLeft;
    private javax.swing.JPanel PRight;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCaculate;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxLoan;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmountInsurance;
    private javax.swing.JLabel lblCapital;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblLoan;
    private javax.swing.JLabel lblMonthly;
    private javax.swing.JLabel lblMonthlyInsurance;
    private javax.swing.JLabel lblMonthlyWInsurance;
    private javax.swing.JLabel lblRate;
    private javax.swing.JLabel lblTotalInsurance;
    private javax.swing.JLabel lblTotalInterest;
    private javax.swing.JLabel lblTotalLoan;
    private javax.swing.JLabel lblinsurance;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmountInsurance;
    private javax.swing.JTextField txtCapital;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtInsurance;
    private javax.swing.JTextField txtMonthly;
    private javax.swing.JTextField txtMonthlyInsurance;
    private javax.swing.JTextField txtMonthlyWInsurance;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtTotalInsurrance;
    private javax.swing.JTextField txtTotalInterest;
    private javax.swing.JTextField txtTotalLoan;
    // End of variables declaration//GEN-END:variables
}
