/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pds_banque.View;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Warren
 */
public class ScreenLoanSim extends JFrame {

    /**
     * Creates new form ScreenLoanSim
     */
    public ScreenLoanSim() {
        initComponents();
        rootPane.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLeft = new JPanel();
        lblLoan = new JLabel();
        cbxLoan = new JComboBox<>();
        lblAmount = new JLabel();
        txtAmount = new JFormattedTextField();
        lblRate = new JLabel();
        txtRate = new JFormattedTextField();
        lblinsurance = new JLabel();
        txtInsurance = new JFormattedTextField();
        lblAmountInsurance = new JLabel();
        txtAmountInsurance = new JFormattedTextField();
        lblDuration = new JLabel();
        txtDuration = new JFormattedTextField();
        lblDate = new JLabel();
        txtDate = new JFormattedTextField();
        lblCapital = new JLabel();
        txtCapital = new JFormattedTextField();
        btnCaculate = new JButton();
        PRight = new JPanel();
        lblMonthly = new JLabel();
        txtMonthly = new JFormattedTextField();
        lblMonthlyWInsurance = new JLabel();
        txtMonthlyWInsurance = new JFormattedTextField();
        lblMonthlyInsurance = new JLabel();
        txtMonthlyInsurance = new JFormattedTextField();
        lblTotalInterest = new JLabel();
        txtTotalInterest = new JFormattedTextField();
        lblTotalInsurance = new JLabel();
        txtTotalInsurrance = new JFormattedTextField();
        lblTotalLoan = new JLabel();
        txtTotalLoan = new JFormattedTextField();
        btnSave = new JButton();
        btnBack = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation de prêt");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("windows"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        PLeft.setBackground(new java.awt.Color(255, 255, 255));
        PLeft.setPreferredSize(new java.awt.Dimension(300, 500));

        lblLoan.setText("Type de prêt");

        cbxLoan.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAmount.setText("Montant du prêt");

        lblRate.setText("Taux d'interêt");

        txtRate.setEditable(false);
        txtRate.setBackground(new java.awt.Color(235, 235, 235));

        lblinsurance.setText("Taux d'assurance");

        lblAmountInsurance.setText("Montant de l'assurance");

        lblDuration.setText("Durée en mois");

        lblDate.setText("Première écheance");

        lblCapital.setText("Apport initial");

        btnCaculate.setText("Calculer");
        org.jdesktop.layout.GroupLayout PLeftLayout = new org.jdesktop.layout.GroupLayout(PLeft);
        PLeft.setLayout(PLeftLayout);
        PLeftLayout.setHorizontalGroup(
            PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PLeftLayout.createSequentialGroup()
                .add(PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PLeftLayout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(lblCapital)
                            .add(lblDuration)
                            .add(lblAmountInsurance)
                            .add(lblinsurance)
                            .add(lblRate)
                            .add(lblAmount)
                            .add(lblLoan)
                            .add(lblDate)
                            .add(cbxLoan, 0, 200, Short.MAX_VALUE)
                            .add(txtAmount)
                            .add(txtRate)
                            .add(txtInsurance)
                            .add(txtAmountInsurance)
                            .add(txtDuration)
                            .add(txtDate)
                            .add(txtCapital)))
                    .add(PLeftLayout.createSequentialGroup()
                        .add(97, 97, 97)
                        .add(btnCaculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(50, 50, 50))
        );
        PLeftLayout.setVerticalGroup(
            PLeftLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PLeftLayout.createSequentialGroup()
                .add(lblLoan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cbxLoan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblAmount)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtAmount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblRate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtRate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblinsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblAmountInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtAmountInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblDuration)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtDuration, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblDate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(lblCapital)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtCapital, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnCaculate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PRight.setBackground(new java.awt.Color(255, 255, 255));
        PRight.setPreferredSize(new java.awt.Dimension(300, 500));

        lblMonthly.setText("Mensualité hors assurance");

        txtMonthly.setEditable(false);
        txtMonthly.setBackground(new java.awt.Color(235, 235, 235));

        lblMonthlyWInsurance.setText("Mensualité de l'assurance");

        txtMonthlyWInsurance.setEditable(false);
        txtMonthlyWInsurance.setBackground(new java.awt.Color(235, 235, 235));

        lblMonthlyInsurance.setText("Mensualité avec assurrance");

        txtMonthlyInsurance.setEditable(false);
        txtMonthlyInsurance.setBackground(new java.awt.Color(235, 235, 235));

        lblTotalInterest.setText("Total interets");

        txtTotalInterest.setEditable(false);
        txtTotalInterest.setBackground(new java.awt.Color(235, 235, 235));

        lblTotalInsurance.setText("Total assurance");

        txtTotalInsurrance.setEditable(false);
        txtTotalInsurrance.setBackground(new java.awt.Color(235, 235, 235));

        lblTotalLoan.setText("Cout total du prêt");

        txtTotalLoan.setEditable(false);
        txtTotalLoan.setBackground(new java.awt.Color(235, 235, 235));

        btnSave.setText("Enregister");

        org.jdesktop.layout.GroupLayout PRightLayout = new org.jdesktop.layout.GroupLayout(PRight);
        PRight.setLayout(PRightLayout);
        PRightLayout.setHorizontalGroup(
            PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PRightLayout.createSequentialGroup()
                .add(50, 50, 50)
                .add(PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTotalInsurance)
                    .add(lblTotalInterest)
                    .add(lblMonthlyInsurance)
                    .add(lblMonthlyWInsurance)
                    .add(lblMonthly)
                    .add(lblTotalLoan)
                    .add(txtMonthly, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .add(txtMonthlyWInsurance)
                    .add(txtMonthlyInsurance)
                    .add(txtTotalInterest)
                    .add(txtTotalInsurrance)
                    .add(txtTotalLoan))
                .add(50, 50, 50))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PRightLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(97, 97, 97))
        );
        PRightLayout.setVerticalGroup(
            PRightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PRightLayout.createSequentialGroup()
                .add(65, 65, 65)
                .add(lblMonthly)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthly, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblMonthlyWInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthlyWInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblMonthlyInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtMonthlyInsurance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalInterest)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalInterest, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalInsurance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalInsurrance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(lblTotalLoan)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtTotalLoan, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnSave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnBack.setText("Retour");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .add(PLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 40, Short.MAX_VALUE)
                .add(PRight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PLeft, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .add(PRight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel PLeft;
    private JPanel PRight;
    private JButton btnBack;
    private JButton btnCaculate;
    private JButton btnSave;
    private JComboBox<String> cbxLoan;
    private JLabel lblAmount;
    private JLabel lblAmountInsurance;
    private JLabel lblCapital;
    private JLabel lblDate;
    private JLabel lblDuration;
    private JLabel lblLoan;
    private JLabel lblMonthly;
    private JLabel lblMonthlyInsurance;
    private JLabel lblMonthlyWInsurance;
    private JLabel lblRate;
    private JLabel lblTotalInsurance;
    private JLabel lblTotalInterest;
    private JLabel lblTotalLoan;
    private JLabel lblinsurance;
    private JFormattedTextField txtAmount;
    private JFormattedTextField txtAmountInsurance;
    private JFormattedTextField txtCapital;
    private JFormattedTextField txtDate;
    private JFormattedTextField txtDuration;
    private JFormattedTextField txtInsurance;
    private JFormattedTextField txtMonthly;
    private JFormattedTextField txtMonthlyInsurance;
    private JFormattedTextField txtMonthlyWInsurance;
    private JFormattedTextField txtRate;
    private JFormattedTextField txtTotalInsurrance;
    private JFormattedTextField txtTotalInterest;
    private JFormattedTextField txtTotalLoan;
    // End of variables declaration//GEN-END:variables
}
