/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pds_banque.View;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import pds_banque.Controller.ControllerScreenCreateCust;
import pds_banque.Controller.ControllerScreenDeleteCust;
import pds_banque.Model.AccessDB;
import pds_banque.Model.ModifiedFocusPolicy;

/**
 *
 * @author florent
 */
public class ScreenDeleteCust extends javax.swing.JFrame {

    private final int idC;
    private final AccessDB db;
    private final ArrayList<String> allCust;
    /**
     * Creates new form ScreenDeleteCust
     * @param idC0
     * @throws java.sql.SQLException
     */
    public ScreenDeleteCust(int idC0) throws SQLException {
        initComponents();
        this.idC = idC0;
        this.db = AccessDB.getAccessDB();
        this.allCust = db.getAllCustomers();
        System.out.println("allCustomer "+ allCust);
        for(int i =0; i<allCust.size();i++)
        {
            if((i%3)==1)
            allCustomer.addItem(allCust.get(i-1));
        }
        
        btnSubmit.addActionListener(new ControllerScreenDeleteCust(this,allCustomer,idC0, btnSubmit, btnBack));
        btnBack.addActionListener(new ControllerScreenDeleteCust(this, idC, btnBack, btnSubmit));

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        allCustomer = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        allCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectionner" }));

        jLabel2.setText("Customer");

        btnSubmit.setText("Valider");

        btnBack.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addGap(34, 34, 34)
                        .addComponent(btnBack))
                    .addComponent(allCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox allCustomer;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
