/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.god.views;

import edu.god.controllers.ControllerScreenCompareSimulation;
import edu.god.models.AccessDB;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author florent
 */
public class ScreenCompareSimulation extends javax.swing.JFrame {

    /**
     * Creates new form ScreenCompareSimulation
     */
    private int idCustomer;
    private AccessDB db;
    
    public ScreenCompareSimulation(int idCustomer0) throws SQLException {
        initComponents();
        this.idCustomer = idCustomer0;
        loadDataInTable(AccessDB.getAccessDB().getSimulationsLoanOfCustomer(idCustomer0));
        this.setVisible(true);
        btnClose.addActionListener(new ControllerScreenCompareSimulation(this,btnClose));
    }

    public void loadDataInTable(ArrayList<String[]> simulations) {
        DefaultTableModel model = (DefaultTableModel) tableCompareSims.getModel();
        
        //tableCompareSims.setEnabled(false);
        for (String[] sim : simulations) {            
            model.addRow(sim);
        }
        tableCompareSims.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCompareSims = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Comparaison Simulation");

        tableCompareSims.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Choix", "Type", "Capital", "Interet", "Mens Pret", "Mens Ass", "Duree", "Total à rembourser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCompareSims);
        if (tableCompareSims.getColumnModel().getColumnCount() > 0) {
            tableCompareSims.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableCompareSims.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableCompareSims.getColumnModel().getColumn(2).setPreferredWidth(100);
            tableCompareSims.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableCompareSims.getColumnModel().getColumn(4).setPreferredWidth(100);
            tableCompareSims.getColumnModel().getColumn(5).setPreferredWidth(50);
            tableCompareSims.getColumnModel().getColumn(6).setPreferredWidth(50);
            tableCompareSims.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        btnClose.setText("Fermer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCompareSims;
    // End of variables declaration//GEN-END:variables
}
