/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.god.views;
import edu.god.models.AccessDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.nio.file.Files.*;
import static java.rmi.Naming.*;
import java.sql.SQLException;
import static java.util.Collections.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Coline
 */
public class ScreenType extends javax.swing.JFrame {
    private final AccessDB bdd;
    private int idConsultant;
    /**
     * Creates new form ScreenType
     */
    public ScreenType(int idConsultant) {
        initComponents();
        this.bdd =AccessDB.getAccessDB();
        this.idConsultant=idConsultant;
      System.out.println(idConsultant);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choissisez le type de prêt ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consommation", "Personnel", "Travaux", "Immobilier", "Rachat de credit", "Vehicules" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(151, 151, 151)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Come back in Home
        ScreenHome  screen = new ScreenHome(1);
        screen.setVisible(true);
      //Delete window
        this. setVisible(false);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String[] possibilites = {"Consommation", "Personnel", "Immobilier","Travaux", "Rachat de credit","Vehicules"};


                String s = (String) jComboBox1.getSelectedItem();
                switch (s) {
                    /*Clic on case Consuption*/
                    case "Consommation":
                        ScreenModifyRatesConsumption screen;
       try {
           /*window if choice Consumption*/
           screen = new ScreenModifyRatesConsumption(idConsultant);
           screen.setVisible(true);
           /*not visible window screentype*/
                       this. setVisible(false);
                       this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }
                        break;
/*Clic on case Personal*/
                    case "Personnel":
                        ScreenModifyRatesPersonal screenP;
       try {
           screenP = new ScreenModifyRatesPersonal(idConsultant);
           screenP.setVisible(true);
                       this. setVisible(false);
                       this.dispose();// Ce qui se passe
       } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }
       break;
       /*Clic on case Property*/
                    case "Immobilier":
                         ScreenModifyRatesProperty screenI;
       try {
           screenI = new ScreenModifyRatesProperty(idConsultant);
            screenI.setVisible(true);
                       this. setVisible(false);
                       this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }                 
                        break;
                        /*Clic on case Project*/
                    case "Travaux":
                         ScreenModifyRatesProject screenT;
       try {
           screenT = new ScreenModifyRatesProject(idConsultant);
           screenT.setVisible(true);
                       this. setVisible(false);
                       this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }
                        break;
            /*Clic on case Repurchase*/
                    case "Rachat de credit":
                        ScreenModifyRatesRepurchase screenR;
                        try{
                           screenR = new ScreenModifyRatesRepurchase(idConsultant);
                        screenR.setVisible(true);
                       this. setVisible(false);
                       this.dispose();
                        } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }
                        break;
            /*Clic on case Vehicles*/
                      case "Vehicules":
               ScreenModifyRatesVehicles screenV;
       try {
           screenV = new ScreenModifyRatesVehicles(idConsultant);
           screenV.setVisible(true);
                       this. setVisible(false);
                       this.dispose();
       } catch (SQLException ex) {
           Logger.getLogger(ScreenType.class.getName()).log(Level.SEVERE, null, ex);
       }
                        break;
                    default:
                                           
                        System.out.println("Vous devez selectionné un type de taux");
                        break;
                
            
        };
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
